### ISSUE TITLE
type object 'object' has no attribute 'name' Traceback

### ISSUE THREAD

**Issue by tripoflgb** [Steffo99/greed#120]
Hello, please help me! I'm When I want to place an order, I get an error after I add the item to the cart and click "Checkout". Thank you.

## Describe the bug

: type object 'object' has no attribute 'name'
Traceback (most recent call last):
  File "/srv/greed/worker.py", line 204, in run
    self.__user_menu()
  File "/srv/greed/worker.py", line 473, in __user_menu
    self.__order_menu()
  File "/srv/greed/worker.py", line 676, in __order_menu
    self.__order_transaction(order=order, value=-int(self.__get_cart_value(cart)                                             ))
  File "/srv/greed/worker.py", line 699, in __order_transaction
    payment_name=(self.order_info.name if self.order_info.name else None),
AttributeError: type object 'object' has no attribute 'name'

**Comment by valentino-sm** [comment]
fixed.
related to #119

**Comment by Steffo99** [comment]
This is an issue about a development branch, it's not my responsibility to fix it, sorry :P
