### ISSUE TITLE
Error with pull n88 "Categories implementation"

### ISSUE THREAD

**Issue by tripoflgb** [Steffo99/greed#128]
Hello! Thanks.

Please help, if use this update - i have error:
`Traceback (most recent call last): File "/srv/tlbot/worker.py", line 215, in run self.__admin_menu() File "/srv/tlbot/worker.py", line 1053, in __admin_menu self.__products_menu() File "/srv/tlbot/worker.py", line 1120, in __products_menu self.__edit_product_menu(product=product) File "/srv/tlbot/worker.py", line 1223, in __edit_product_menu if not price == None: File "/srv/tlbot/worker.py", line 114, in __eq__ return self.value == Price(other).value AttributeError: 'Price' object has no attribute 'value'`

Can you please tell me, does this error appear when I use this update of files with categories?

**Comment by Steffo99** [comment]
I don't know, that pull request hasn't been merged because I requested changes from its author which haven't been done yet.

You should probably ask them in #88!
