### ISSUE TITLE
Help! How add Notification

### ISSUE THREAD

**Issue by tripoflgb** [Steffo99/greed#134]
Hello! Help! How add Notification to all users from bd.User, when add new products???

Thanks.

**Comment by Steffo99** [comment]
Please explain in more detail, I have no idea of what you mean...

**Comment by tripoflgb** [comment]
> Please explain in more detail, I have no idea of what you mean...

Good day! I need that after adding a product, this product is sent as news to everyone who interacted with the bot, these are users of the bd.Users database.

An example - https://dev.to/princematthew/how-to-send-messages-to-all-users-that-interact-with-a-telegram-bot-3394, how can you integrate this solution into your bot ??

**Comment by tripoflgb** [comment]
> Please explain in more detail, I have no idea of what you mean...

I know that I need to take all the user_id users from the database, and send them to them via telegram.Message

**Comment by Steffo99** [comment]
> > Please explain in more detail, I have no idea of what you mean...
> 
> Good day! I need that after adding a product, this product is sent as news to everyone who interacted with the bot, these are users of the bd.Users database.
> 
> An example - https://dev.to/princematthew/how-to-send-messages-to-all-users-that-interact-with-a-telegram-bot-3394, how can you integrate this solution into your bot ??

The Telegram bot guidelines don't allow this, as it might be considered spamming; that's why it's not implemented...

**Comment by Steffo99** [comment]
I suggest you make a Telegram channel and add your clients to it, so they that they may be notified of news about your shop.
