### ISSUE TITLE
greedtestbot is broken

### ISSUE THREAD

**Issue by nmatton** [Steffo99/greed#137]
## Describe the bug

When starting a new conversation with /start, nothings happens

## To reproduce

1. Go to the bot @greedtestbot
2. send /start

## Expected behavior

The bot start the conversation, etc.

## Screenshots

[screenshot available here](https://tgtgnotif.rocks/signal-2021-06-03-123220.png)

## Additional context

I already joined the bot few weeks ago but wanted to get back in touch and have better insight and maybe start with it...

**Comment by Steffo99** [comment]
Should be working now ^^
