### ISSUE TITLE
Split products into multiple categories

### ISSUE THREAD

**Issue by DarrenWestwood** [Steffo99/greed#164]
## Describe the feature
Split products into multiple categories (like electronics, clothes, food) instead of grouping them in a single catalog

## Reasoning for the implementation
Improves locating specific products and browsing products in larger stores with a wide range of products

## Additional information
Originally requested by users in another fork: https://github.com/DarrenWestwood/greed/issues/22

**Comment by Steffo99** [comment]
Duplicate of #33 :)
