### ISSUE TITLE
Support deployment via Docker

### ISSUE THREAD

**Issue by Somnius** [Steffo99/greed#167]
## Docker / Composer
Need for this project to exist as a docker image so all configuration could be done in native env/venv

## Reasoning for the implementation
To be easier for users to test things out before going public with their bot, easier to deploy on cheap vps with e.g. alpine linux distro's installed.

## Additional information
No additional information added.

Thank you

**Comment by Steffo99** [comment]
There's an open pull request for that: #102.

I haven't got to merging it yet, but it should work fine for your needs!
