### ISSUE TITLE
Feature: Publish docker image on DockerHub

### ISSUE THREAD

**Issue by yayitazale** [Steffo99/greed#180]
### Describe the proposed feature

Just publish the builded docker images on dockerhub

### Reasoning

Publishing this image in docker hub will make easier to install it as a service in some environments like Unraid.

**Comment by Steffo99** [comment]
Check out if [the instructions here](https://github.com/Steffo99/greed/pkgs/container/greed) help you out.

**Comment by yayitazale** [comment]
I have tried and yes it works, I will create a template to publish it on community apps library.
