### ISSUE TITLE
Bug: Flood control exceeded

### ISSUE THREAD

**Issue by jashvakharia** [Steffo99/greed#210]
### Describe the bug

flood control

### Steps to reproduce the behavior

just started the bot
this is the log

https://katb.in/odogazoqese

**Comment by Steffo99** [comment]
You've exceeded Telegram's rate limits.

Can you provide debug logs?

Set the logging level to DEBUG in the configuration file:

```
[Logging]
level = "DEBUG"
```

**Comment by jashvakharia** [comment]
https://katb.in/numataboloh

here

**Comment by jashvakharia** [comment]
> You've exceeded Telegram's rate limits.
> 
> Can you provide debug logs?
> 
> Set the logging level to DEBUG in the configuration file:
> 
> ```toml
> [Logging]
> level = "DEBUG"
> ```

can this be an issue of using it in WSL?

**Comment by jashvakharia** [comment]
> You've exceeded Telegram's rate limits.
> 
> Can you provide debug logs?
> 
> Set the logging level to DEBUG in the configuration file:
> 
> ```toml
> [Logging]
> level = "DEBUG"
> ```

https://katb.in/numataboloh

here is the log too

**Comment by Steffo99** [comment]
Seems like you added the bot to a group. That's not supported; please remove it as it mentions so it stops sending the `error_nonprivate_chat` message!

**Comment by jashvakharia** [comment]
so it's like even if i'm not contacting the bot in group, it will keep sending that message?

**Comment by Steffo99** [comment]
Yup!

**Comment by jashvakharia** [comment]
oh damn. thank you alot! could you maybe help me figuring out the previous feature issue i created? if possible.
