### ISSUE TITLE
Doesn’t display multiple in store. 

### ISSUE THREAD

**Issue by herrjunkie** [Steffo99/greed#227]
It allowed m to upload multiple pic, but when I went to store as user I wasn’t able to view the multiple uploaded. 

Like if I want to upload the front and back pic I am item. 

![21317181-FBF0-40D1-B30C-1BF921BFFA0D](https://github.com/Steffo99/greed/assets/161686650/ca736023-5abd-47b5-9a30-801df373e77e)
![ED32033F-25ED-449C-9ED4-4007E8387A39](https://github.com/Steffo99/greed/assets/161686650/a34a0e34-4201-4afc-96ba-662b0cf5e1b7)

**Comment by Steffo99** [comment]
Greed currently supports only a single picture per product...

Sadly, there's no way to prevent an user from sending multiple pictures.

Maybe an error message should be displayed instead?

**Comment by herrjunkie** [comment]
I’m a new python student, self taught, and trying to make changes to the code. Instead of using credit, I want the user to b able to pay directly, I do get some errors. Can I share maybe I’d learn a few thing from you. I haven’t worked on a bot before

**Comment by Steffo99** [comment]
No, sorry, I'm not available for teaching...
