### ISSUE TITLE
Bug: When I change the currency in config, for some reason it does not change when the bot is launched

### ISSUE THREAD

**Issue by seniy123** [Steffo99/greed#231]
### Describe the bug

When I change the currency in config, for some reason it does not change when the bot is launched. Can you please tell me what needs to be done to fix this

### Steps to reproduce the behavior

![Снимок экрана 2024-05-11 121944](https://github.com/Steffo99/greed/assets/148769476/524513ff-e042-4066-a445-e095a552e521)
![Снимок экрана 2024-05-11 122011](https://github.com/Steffo99/greed/assets/148769476/c97e77b5-0ac6-4717-b3fe-1f0c70d46463)

**Comment by Steffo99** [comment]
You're supposed to create your config in `config.toml`, not `template_config.toml` :)

**Comment by seniy123** [comment]
ahahah, thank you very much. There may be more questions, I hope I'm not
distracting you too much

вс, 12 мая 2024 г. в 12:50, Stefano Pigozzi ***@***.***>:

**Comment by seniy123** [comment]
ahahah, thank you very much. Will it be possible to add a Russian card?
There may be more questions, I hope I'm not distracting you too much

вс, 12 мая 2024 г. в 12:50, Stefano Pigozzi ***@***.***>:
