### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by GuyFawkesII** [Steffo99/greed#24]
when I run :
$python3.6 -00 core.py
I get this error 
------------------------------------------------------------------
Unauthorized to call get_me(), skipping.
greed-bot is now starting!
Unauthorized to call get_updates(), skipping.
Traceback (most recent call last):
  File "core.py", line 123, in <module>
    main()
  File "core.py", line 43, in main
    for update in updates:
TypeError: 'NoneType' object is not iterable

How can I resolve this issue 
Thanks

**Comment by Steffo99** [comment]
The Telegram API key you entered in the config file is invalid, please try with a working one.
