### ISSUE TITLE
How to remove a restriction on a transaction?

### ISSUE THREAD

**Issue by HarleyK1ng** [Steffo99/greed#27]
Hello! The maximum number is 3 digits, but I would like to have no restrictions. Thank!

**Comment by Steffo99** [comment]
You should be able to change the `max_amount` setting in the config.ini :)

You can check the hard maximum allowed amount in the [currencies.json](https://core.telegram.org/bots/payments/currencies.json) file distributed by Telegram; for Euros, that is `893455`.

**Comment by HarleyK1ng** [comment]
Of course, I changed the value of max_amount and no difference. Set as in the json file as well as 9999999999 and otherwise. Always a maximum of 3 digits. That is, from 1 to 999.

**Comment by Steffo99** [comment]
Uhhhh, that's weird.

Can you send me some more info, such a Telegram screenshot?

**Comment by Steffo99** [comment]
I fixed your issue! Sorry if I didn't understand immediatly 😅
