### ISSUE TITLE
how can add products and browse them by category ?

### ISSUE THREAD

**Issue by GuyFawkesII** [Steffo99/greed#29]
how can add products and browse them by category ?

**Comment by Steffo99** [comment]
What?

**Comment by Bradobrei** [comment]
Ciao, aiuto , per favore, come fare l'aggiunta di un prodotto in diverse categorie separatamente (Pizza, Panini, Pasta), e non in un catalogo in una sola volta? Grazie

**Comment by Steffo99** [comment]
I think #33 is what you meant. Closing this issue...
