### ISSUE TITLE
La valuta del prezzo non cambia

### ISSUE THREAD

**Issue by Bradobrei** [Steffo99/greed#34]
Un'altra domanda, la valuta dei Prezzi rimane costantemente in euro, anche se il file config. ini è stato modificato come hai detto? Grazie

**Comment by Steffo99** [comment]
In che senso?

Il simbolo utilizzato per la valuta è specificato nel file strings selezionato, ad esempio: 

https://github.com/Steffo99/greed/blob/2b23bd56613cdac91abfbb905b48bce00799a040/strings/it_IT.py#L6

**Comment by Bradobrei** [comment]
Sono disattento, mi dispiace, lascia che tutto vada bene in Italia, grazie
