### ISSUE TITLE
Wrong keyboard layout in admin Orders menu

### ISSUE THREAD

**Issue by pzhuk** [Steffo99/greed#39]
How to reproduce:

1) Enter admin Orders menu
2) Try to Complete or Refund any order
3) Only way to exit this menu is to find Stop button somewhere in the chat history.
    Try to open a keyboard layout - main menu keyboard is displayed, but no any actions are possible, because the only expected command to return the menu selection is Stop command

**Comment by Steffo99** [comment]
That's the intended behaviour. It's what I call the **Live Order mode**. I admit it's not the best possible user experience, but at the time it was the best idea that came to my mind.

Do you have any ideas on how to improve it?

**Comment by pzhuk** [comment]
I understand and like this feature of Live Order mode
Problem is that during this live order mode - keyboard is wrong. If you unhide the keyboard and try to use any option - nothing happens.

My improvement suggestion would be -  to put a proper keyboard in the Live mode having a Stop button there

**Comment by Steffo99** [comment]
Oh. I understand, and you're right.

I'll see what can be done when I come back to this project.

Thanks for the report! 😄
