### ISSUE TITLE
Cannot view transaction list

### ISSUE THREAD

**Issue by DarrenWestwood** [Steffo99/greed#61]
The Transaction list from the admin menu does not load transactions if any are present. The error can be replicated on a new installation from the master branch.

Steps to replicate:
Create transactions manually from admin panel > Transaction list
`Full error: Can't parse entities: unsupported start tag "transaction" at byte offset 16`

**Comment by Steffo99** [comment]
oh, I thought I fixed all instances of this bug yesterday

fixing it now
