### ISSUE TITLE
Use cases for the bot

### ISSUE THREAD

**Issue by Steffo99** [Steffo99/greed#65]
Hi everyone!

I'd like to know if anyone is currently using Greed in a production environment!

If you do, please post a reply at this issue describing where and how you use it :)

**Comment by urba1n** [comment]
Thinking of hosting a few free bots to help local businesses to sell their products during closing involved by covid. But paiement/wallet seems too complicated so pay cash (or anyway, but at delivery) could be nice. Did you already reconsider this feature ?

**Comment by Steffo99** [comment]
@urba1n What?
