### ISSUE TITLE
Scape of the keys in file string 

### ISSUE THREAD

**Issue by tomtomaZ** [Steffo99/greed#82]
I tried to insert some strings of my own in the language files, but as braces called "{...}" it doesn't work in the new messages I created even following a syntax, maybe it is an error in the localization.py formation

1. Go to wathever string file
2. try create a new message format using the standard keys
3. when a tested the key did showed, like "{name}", but works in messages that were already there

**Comment by Steffo99** [comment]
Can you please provide an example key that doesn't work with the relative `self.loc` call?

**Comment by tomtomaZ** [comment]
Just a call that i create dosen't work withi self.loc.get(), i create a call called "conversation_click_add_cart", and in his string in a pt_br.py i used a product of name key, the message is showed but the key is not converted for the value, showing {name} in message

**Comment by Steffo99** [comment]
Have you passed the key as a keyword argument in the `self.loc.get` call?

Can you please send me the problematic line(s) of code?

**Comment by Steffo99** [comment]
> you need to pass `name` in the `self.loc.get` call
> ```python
> self.loc.get("conversation_click_add_cart", name="your string")
> ```
