### ISSUE TITLE
refill on checkout

### ISSUE THREAD

**Issue by deeankin** [Steffo99/greed#91]
If there is 0 money on the balance, then the account payment is not initialized with the help, it is proposed to top up the balance. If the balance is greater than 0, then the function works.
refill_on_checkout = true
Localization = Ru
but I tried other localizations, this does not solve the problem
2020-12-25 22:28:53,718 | Worker 216439094 | localization | Missing localized string with key menu_language, using default

**Comment by Steffo99** [comment]
?
