### ISSUE TITLE
TypeError: int() in worker.py, line 1062

### ISSUE THREAD

**Issue by tripoflgb** [Steffo99/greed#95]
Hello! 
Dear, please help my, i get an error when flagging an item as out of stock. How to fix the error?

 File "/root/greed/worker.py", line 1062, in __edit_product_menu
    product.price = int(price) if not isinstance(price, CancelSignal) else product.price
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Steffo99** [comment]
I think it's a legitimate bug, I'll have a look at it in the next 15 mins.

**Comment by Steffo99** [comment]
Try to update the bot with `git pull`, and then please tell me if the bug still occours.
